name: Deploy to EC2

on:
  push:
    branches: [ master, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Notify EC2 to pull and deploy
      env:
        EC2_WEBHOOK_URL: ${{ secrets.EC2_WEBHOOK_URL }}
      run: |
        # Notificar a la EC2 para que actualice el código y reinicie el servicio
        curl -X POST $EC2_WEBHOOK_URL
        echo "Notificación enviada a la instancia EC2"
